import Head from "next/head";
import { useEffect, useState } from "react";
import { getPartnerTrainingLayout } from "../../../components/Layout";
import { partnerAPI } from "../../../services/api";

type ImpactSummary = {
  summary: {
    total_requests: number;
    approved_requests: number;
    pending_requests: number;
    rejected_requests: number;
    average_confidence_pct: number;
    jobs_created: number;
    linked_users: number;
    verified_professionals: number;
  };
  esg: {
    total_impact_score: number;
    total_co2_avoided_kg: number;
    recycled_projects: number;
    active_projects: number;
    total_panels: number;
    total_batteries: number;
  };
  projects: {
    total_verified_user_projects: number;
    pending_recovery_projects: number;
    recycled_projects: number;
  };
  top_verified_trainees?: Array<{
    user_id: string;
    full_name: string;
    email?: string | null;
    projects_count: number;
    recycled_projects_count: number;
    impact_score: number;
    co2_avoided_kg: number;
  }>;
};

export default function TrainingImpactPage() {
  const [impact, setImpact] = useState<ImpactSummary | null>(null);

  useEffect(() => {
    void partnerAPI
      .trainingImpactSummary()
      .then((response) => setImpact((response.data?.data || null) as ImpactSummary | null))
      .catch(() => setImpact(null));
  }, []);
  const summary = impact?.summary;
  const esg = impact?.esg;
  const projects = impact?.projects;
  const topTrainees = impact?.top_verified_trainees || [];

  return (
    <>
      <Head>
        <title>Institute Impact — SolNuv</title>
      </Head>
      <div className="max-w-4xl">
        <h1 className="text-2xl font-bold text-forest-900 dark:text-white mb-2">Institute impact</h1>
        <p className="text-sm text-slate-600 dark:text-slate-300 mb-6">
          ESG and workforce impact generated by professionals verified through your institute.
        </p>

        <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4">
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
            <p className="text-xs uppercase text-slate-500">Total requests</p>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1">{summary?.total_requests ?? 0}</p>
          </div>
          <div className="rounded-xl border border-emerald-200 dark:border-emerald-900/50 bg-emerald-50/70 dark:bg-emerald-950/25 p-4">
            <p className="text-xs uppercase text-emerald-700 dark:text-emerald-300">Approved</p>
            <p className="text-2xl font-bold text-emerald-800 dark:text-emerald-200 mt-1">{summary?.approved_requests ?? 0}</p>
          </div>
          <div className="rounded-xl border border-amber-200 dark:border-amber-900/50 bg-amber-50/70 dark:bg-amber-950/25 p-4">
            <p className="text-xs uppercase text-amber-700 dark:text-amber-300">Pending</p>
            <p className="text-2xl font-bold text-amber-800 dark:text-amber-200 mt-1">{summary?.pending_requests ?? 0}</p>
          </div>
          <div className="rounded-xl border border-red-200 dark:border-red-900/50 bg-red-50/70 dark:bg-red-950/25 p-4">
            <p className="text-xs uppercase text-red-700 dark:text-red-300">Rejected</p>
            <p className="text-2xl font-bold text-red-800 dark:text-red-200 mt-1">{summary?.rejected_requests ?? 0}</p>
          </div>
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
            <p className="text-xs uppercase text-slate-500">Avg confidence</p>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1">{summary?.average_confidence_pct ?? 0}%</p>
          </div>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-4">
          <div className="rounded-xl border border-emerald-200 dark:border-emerald-900/50 bg-emerald-50/70 dark:bg-emerald-950/25 p-4">
            <p className="text-xs uppercase text-emerald-700 dark:text-emerald-300">ESG impact score</p>
            <p className="text-2xl font-bold text-emerald-800 dark:text-emerald-200 mt-1">
              {(esg?.total_impact_score ?? 0).toLocaleString()}
            </p>
          </div>
          <div className="rounded-xl border border-sky-200 dark:border-sky-900/50 bg-sky-50/70 dark:bg-sky-950/25 p-4">
            <p className="text-xs uppercase text-sky-700 dark:text-sky-300">CO2 avoided</p>
            <p className="text-2xl font-bold text-sky-800 dark:text-sky-200 mt-1">
              {(esg?.total_co2_avoided_kg ?? 0).toLocaleString()} kg
            </p>
          </div>
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
            <p className="text-xs uppercase text-slate-500">Jobs created</p>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1">{summary?.jobs_created ?? 0}</p>
          </div>
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
            <p className="text-xs uppercase text-slate-500">Verified professionals</p>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1">{summary?.verified_professionals ?? 0}</p>
          </div>
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
            <p className="text-xs uppercase text-slate-500">Verified user projects</p>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1">{projects?.total_verified_user_projects ?? 0}</p>
          </div>
          <div className="rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
            <p className="text-xs uppercase text-slate-500">Recycled projects</p>
            <p className="text-2xl font-bold text-slate-900 dark:text-white mt-1">{projects?.recycled_projects ?? 0}</p>
          </div>
        </div>

        <div className="mt-6 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900/40 p-4">
          <h2 className="text-sm font-semibold text-slate-900 dark:text-white mb-3">Top verified trainees</h2>
          {topTrainees.length === 0 ? (
            <p className="text-sm text-slate-500">No verified trainee impact data available yet.</p>
          ) : (
            <div className="space-y-2">
              {topTrainees.map((trainee, index) => (
                <div
                  key={trainee.user_id}
                  className="rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50/70 dark:bg-slate-900/50 px-3 py-2"
                >
                  <div className="flex items-center justify-between gap-3">
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-slate-900 dark:text-white truncate">
                        #{index + 1} {trainee.full_name}
                      </p>
                      <p className="text-xs text-slate-500 truncate">{trainee.email || "No public email"}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-slate-500">Impact score</p>
                      <p className="text-sm font-semibold text-emerald-700 dark:text-emerald-300">
                        {trainee.impact_score.toLocaleString()}
                      </p>
                    </div>
                  </div>
                  <div className="mt-2 grid sm:grid-cols-3 gap-2 text-xs text-slate-600 dark:text-slate-300">
                    <p>Projects: {trainee.projects_count}</p>
                    <p>Recycled: {trainee.recycled_projects_count}</p>
                    <p>CO2 avoided: {trainee.co2_avoided_kg.toLocaleString()} kg</p>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </>
  );
}

TrainingImpactPage.getLayout = getPartnerTrainingLayout;
