/**
 * SolNuv Export Pack Service
 *
 * Bundles a single simulation result into a reproducible ZIP archive:
 *
 *   SolNuv_Export_<project>_<date>.zip
 *   ├─ README.md                — human-readable index (engine version, inputs hash)
 *   ├─ report.pdf               — branded design report
 *   ├─ report.xlsx              — tabular cashflow + monthly summary (best effort)
 *   ├─ inputs.json              — project + design snapshot (the exact inputs)
 *   ├─ results.json             — headline metrics + structured outputs
 *   ├─ provenance.json          — run_provenance blob (engine, weather, tariff, hash)
 *   └─ extended_metrics.json    — pv_loss_waterfall, financial_risk, etc.
 *
 * This is the durable, auditable deliverable: anyone who receives the pack
 * can reconstruct *exactly* which engine version, weather source, and tariff
 * band produced the numbers — the same role a PVsyst project file plays in
 * traditional engineering workflows.
 */

const archiver = require('archiver');
const supabase = require('../config/database');
const {
  generateDesignReportPdf,
  generateDesignReportExcel,
} = require('./designReportService');
const { computeDesignReportV2 } = require('./reportComputeService');
const { SIMULATION_ENGINE_VERSION } = require('../constants/simulationVersion');
const logger = require('../utils/logger');

function safeStringify(value: any): string {
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return JSON.stringify({ error: 'unserializable' }, null, 2);
  }
}

function buildReadme(opts: any): string {
  const {
    project,
    design,
    result,
    provenance,
    generatedAt,
  } = opts;

  const inputsHash = provenance?.inputs_hash || 'n/a';
  const engineVersion = provenance?.engine_version || SIMULATION_ENGINE_VERSION;
  const weather = provenance?.weather || {};
  const tariff = provenance?.tariff || {};

  const lines = [
    `# SolNuv Export Pack`,
    ``,
    `**Project:** ${project?.name || '(unnamed)'}`,
    `**Client:** ${project?.client_name || '—'}`,
    `**Location:** ${project?.city || ''}${project?.state ? ', ' + project.state : ''}`,
    `**Generated:** ${generatedAt}`,
    ``,
    `## Reproducibility`,
    ``,
    `| Field | Value |`,
    `|---|---|`,
    `| Engine version | \`${engineVersion}\` |`,
    `| Inputs hash | \`${inputsHash}\` |`,
    `| Run timestamp | ${result?.run_at || provenance?.generated_at || generatedAt} |`,
    `| Weather source | ${weather.source || '—'} |`,
    `| Weather fetched | ${weather.fetched_at || '—'} |`,
    `| Weather cache hit | ${weather.cache_hit === undefined ? '—' : String(weather.cache_hit)} |`,
    `| Tariff structure | ${tariff.tariff_structure_id || '—'} |`,
    `| Tariff as-of | ${tariff.as_of || '—'} |`,
    `| Tariff band hash | \`${tariff.band_hash || '—'}\` |`,
    ``,
    `## Contents`,
    ``,
    `- \`report.pdf\` — formatted design report (PDF).`,
    `- \`report.xlsx\` — cashflow + monthly summary workbook (if available).`,
    `- \`inputs.json\` — exact project + design inputs used for this run.`,
    `- \`results.json\` — headline metrics and structured outputs.`,
    `- \`provenance.json\` — engine version, input hash, weather and tariff provenance.`,
    `- \`extended_metrics.json\` — PV loss waterfall, Monte Carlo risk bands, etc.`,
    ``,
    `## How to reproduce`,
    ``,
    `1. Install SolNuv simulation engine version \`${engineVersion}\` (or newer with backward-compatible results).`,
    `2. Re-run the simulation using the inputs in \`inputs.json\`.`,
    `3. The resulting \`inputs_hash\` must match \`${inputsHash}\`. Any difference means an input has changed.`,
    `4. If weather or tariff data has been updated since \`${weather.fetched_at || 'run time'}\`, results may drift; the provenance above records what was used.`,
    ``,
    `---`,
    `Generated by SolNuv — https://solnuv.com`,
    ``,
  ];
  return lines.join('\n');
}

/**
 * Build an export pack buffer (ZIP) for a given simulation result.
 * @param {string} simulationResultId
 * @returns {Promise<{buffer: Buffer, filename: string}>}
 */
async function buildExportPack(simulationResultId: string) {
  const { data: result, error: resultError } = await supabase
    .from('simulation_results')
    .select('*')
    .eq('id', simulationResultId)
    .single();
  if (resultError || !result) {
    throw new Error('Simulation result not found: ' + (resultError?.message || 'unknown error'));
  }

  const { data: design } = await supabase
    .from('project_designs')
    .select('*')
    .eq('id', result.project_design_id)
    .single();

  let project: any = null;
  let tariff: any = null;
  let equipment: any[] = [];

  if (design?.project_id) {
    const { data: proj } = await supabase
      .from('projects')
      .select('*, companies(id, name, branding_primary_color)')
      .eq('id', design.project_id)
      .single();
    project = proj;

    const { data: eq } = await supabase
      .from('equipment')
      .select('*')
      .eq('project_id', design.project_id);
    equipment = eq || [];
  }

  if (design?.tariff_structure_id) {
    const { data: t } = await supabase
      .from('tariff_structures')
      .select('*, tariff_rates(*)')
      .eq('id', design.tariff_structure_id)
      .single();
    tariff = t;
  }

  const generatedAt = new Date().toISOString();
  const provenance = result.run_provenance || null;
  const extended = result.extended_metrics || null;

  // Generate PDF + Excel buffers in parallel (best-effort; the pack succeeds even
  // if one of them fails — we never want a brittle dependency to deny an audit).
  const [pdfBuffer, excelBuffer] = await Promise.all([
    generateDesignReportPdf(simulationResultId).catch((err: any) => {
      logger.warn('Export pack: PDF generation failed', { message: err?.message });
      return null;
    }),
    generateDesignReportExcel(simulationResultId).catch((err: any) => {
      logger.warn('Export pack: Excel generation failed', { message: err?.message });
      return null;
    }),
  ]);

  // Strip bulky 8760-hour flows out of the top-level results.json — the PDF
  // already summarizes them and the raw data is huge; keep it in a dedicated
  // file only when present so the pack stays small by default.
  const { hourly_flows, ...resultsWithoutFlows } = result || {};

  const inputsPayload = {
    project: project
      ? {
          id: project.id,
          name: project.name,
          client_name: project.client_name,
          state: project.state,
          city: project.city,
          country_code: project.country_code,
          location_lat: project.location_lat,
          location_lon: project.location_lon,
          installation_date: project.installation_date,
          company: project.companies || null,
        }
      : null,
    design: design || null,
    tariff: tariff || null,
    equipment: equipment || [],
  };

  const resultsPayload = resultsWithoutFlows;
  const provenancePayload = provenance || {
    engine_version: SIMULATION_ENGINE_VERSION,
    note: 'This run predates provenance tracking; audit trail is not available.',
  };
  const extendedPayload = extended || {};

  const readme = buildReadme({
    project,
    design,
    result,
    provenance: provenancePayload,
    generatedAt,
  });

  // Assemble ZIP in memory. archiver streams into a Buffer collector.
  const archive = archiver('zip', { zlib: { level: 9 } });
  const chunks: Buffer[] = [];
  const bufferPromise = new Promise<Buffer>((resolve, reject) => {
    archive.on('data', (chunk: Buffer) => chunks.push(chunk));
    archive.on('end', () => resolve(Buffer.concat(chunks)));
    archive.on('warning', (err: any) => {
      if (err.code !== 'ENOENT') reject(err);
    });
    archive.on('error', reject);
  });

  archive.append(readme, { name: 'README.md' });
  archive.append(safeStringify(inputsPayload), { name: 'inputs.json' });
  archive.append(safeStringify(resultsPayload), { name: 'results.json' });
  archive.append(safeStringify(provenancePayload), { name: 'provenance.json' });
  archive.append(safeStringify(extendedPayload), { name: 'extended_metrics.json' });
  try {
    const reportV2 = await computeDesignReportV2(simulationResultId);
    archive.append(safeStringify(reportV2), { name: 'report_v2.json' });
  } catch (err: any) {
    logger.warn('Export pack: V2 report generation failed', { message: err?.message });
  }
  if (pdfBuffer) archive.append(pdfBuffer, { name: 'report.pdf' });
  if (excelBuffer) archive.append(Buffer.from(excelBuffer), { name: 'report.xlsx' });
  if (hourly_flows) {
    archive.append(safeStringify(hourly_flows), { name: 'hourly_flows.json' });
  }

  await archive.finalize();
  const buffer = await bufferPromise;

  const safeName = (project?.name || 'SolNuv_Project').replace(/[^a-zA-Z0-9]+/g, '_').slice(0, 60);
  const dateStr = generatedAt.slice(0, 10);
  const filename = `SolNuv_Export_${safeName}_${dateStr}.zip`;

  return { buffer, filename };
}

module.exports = {
  buildExportPack,
};
